# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  dabin-Ryu

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


navbar_entries:
  - title: about
    url: about

  - title: blog
    url: blog

  - title: website
    url: https://www.abhinav.co

project_entries:
  - title: Project 1
    url: overview-post
    desc: This is an example project, configured in _data/home.yml

  - title: Project 2
    url: overview-post
    desc: Projects are shown in card layout

  - title: Project 3
    url: overview-post
    desc: You can control visibility from _config.yml file

  - title: Project 4
    url: overview-post
    desc: This project uses highlight markup, configured in _data/home.yml
    highlight: WIP

  - title: Project 5
    url: overview-post
    desc: Moonwalk also has horizontal list (used in header and footer)
    highlight: WIP

  - title: Project 6
    url: overview-post
    desc: It also has a scalable vertical list (in case you need it)

old_project_entries:
  - title: Soopr
    url: https://www.soopr.co
    desc: Delight your readers - add beautiful share and like buttons easily to your websites 
    highlight: NEW

  - title: Cookie
    url: https://github.com/abhinavs/cookie
    desc: An open source landing website with supporting pages and integrated blog

  - title: Moonwalk
    url: https://github.com/abhinavs/moonwalk
    desc: A fast and minimalist Jekyll blog theme with clean dark mode

  - title: Humangous
    url: https://www.humangous.co
    desc: The better people know you, the better they collaborate

footer_entries:
  - title: abhinav's homepage
    url: https://www.abhinav.co

  - title: twitter
    url: https://twitter.com/abhinav

  - title: github
    url: https://github.com/abhinavs

  - title: feed
    url: feed.xml

misc_entries:
  - title: this is an example vertical list
    url: false

  - title: you can show or hide using a boolean flag in _config.yml
    url: false

  - title: and you can add data in _data/home.yml
    url: false

  - title: Blog posts
    post_list: true
    url: false

  - title: moonwalk on the Internet
    url: false
    entries:
      - title: on Github
        url: https://github.com/abhinavs/moonwalk

      - title: originally built for abhinav's homepage
        url: https://www.abhinav.co

      - title: this list is scalable and can be nested
        url: false
        entries:
          - title: this is nested inside a nested list
            url: false

          - title: it is easy to use, see _data/home.yml to see how to configure it.
            url: false


